In [176]:
from dotenv import load_dotenv
import openai
import pandas as pd

load_dotenv()
openai_client = openai.OpenAI()

### Load the knowledge base

In [177]:
import sys
sys.path.append('../src')

from load_index import load_faq_data

documentation = load_faq_data()

In [ ]:
print(documentation)

In [179]:
df = pd.DataFrame(documentation)
df.head()

,id,manual,title,text,url
0,ctm60060,company-taxation-manual,Close companies: general: broad definition,"Subject to certain exceptions, a close company...",https://www.gov.uk/hmrc-internal-manuals/compa...
1,ctm03570,company-taxation-manual,Corporation Tax: small profits relief: associa...,A company is an 'associated company' of anothe...,https://www.gov.uk/hmrc-internal-manuals/compa...
2,ctm61505,company-taxation-manual,Close companies: loans to participators and ar...,CTA10 Part 10 CTA10/S455 applies to loans/adva...,https://www.gov.uk/hmrc-internal-manuals/compa...
3,ctm15205,company-taxation-manual,"Distributions: general: dividends, distributio...",Companies Act 2006 Introduction References are...,https://www.gov.uk/hmrc-internal-manuals/compa...
4,ctm03580,company-taxation-manual,Corporation Tax: small profits relief: associa...,CTM03710 onwards gives detailed guidance on de...,https://www.gov.uk/hmrc-internal-manuals/compa...

In [180]:
df.columns.tolist()

['id', 'manual', 'title', 'text', 'url']

In [181]:
df.manual.value_counts()

manual
paye-manual                  279
vat-registration-manual      263
company-taxation-manual      259
capital-gains-manual         253
capital-allowances-manual    245
Name: count, dtype: int64

In [182]:
len(documentation)

1299

In [183]:
documentation[100]

{'id': 'ctm61555',
 'manual': 'company-taxation-manual',
 'title': 'Close companies: loans to participators: indirect loans: total income',
 'text': 'CTA10/S459 (3) (b) A payment, transfer, release etc, arising from an arrangement described in CTM61550 may be included in the total income of the recipient of the payment. When the amount included in that person’s total income is more than or equal to the amount of the loan or advance, CTA10/S459 will not apply. This may happen, for example, where: a payment to the recipient is treated as his/her income for IT purposes (for example, as a distribution within CTA10/S1000 (1) B or CTA10/S1064, or a loan to the recipient falls within the provisions of ITTOIA05/S633 The ‘total income’ of an individual is defined in ITA07/S23 as the sum of the amounts of income on which the taxpayer is charged to income tax for the tax year. Broadly speaking it consists of earned and investment (or unearned) income. It does not include anything on which capital gains tax is or would be chargeable.',
 'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm61555'}

In [184]:
documentation[100]['id']

'ctm61555'

In [185]:
documentation[100]['manual']

'company-taxation-manual'

In [186]:
documentation[100]['title']

'Close companies: loans to participators: indirect loans: total income'

### index the knowledge base

In [187]:
import minsearch

define the text field for the index for optimal search results. The text field should be a combination of the title and text fields. The keyword field should be the manual field.

In [188]:
from minsearch import Index

index = Index(
    text_fields=["title", "text"],
    keyword_fields=["manual"])

index.fit(documentation)

In [189]:
question = "What counts as capital expenditure for capital allowances purposes?"

In [190]:
df.head()

,id,manual,title,text,url
0,ctm60060,company-taxation-manual,Close companies: general: broad definition,"Subject to certain exceptions, a close company...",https://www.gov.uk/hmrc-internal-manuals/compa...
1,ctm03570,company-taxation-manual,Corporation Tax: small profits relief: associa...,A company is an 'associated company' of anothe...,https://www.gov.uk/hmrc-internal-manuals/compa...
2,ctm61505,company-taxation-manual,Close companies: loans to participators and ar...,CTA10 Part 10 CTA10/S455 applies to loans/adva...,https://www.gov.uk/hmrc-internal-manuals/compa...
3,ctm15205,company-taxation-manual,"Distributions: general: dividends, distributio...",Companies Act 2006 Introduction References are...,https://www.gov.uk/hmrc-internal-manuals/compa...
4,ctm03580,company-taxation-manual,Corporation Tax: small profits relief: associa...,CTM03710 onwards gives detailed guidance on de...,https://www.gov.uk/hmrc-internal-manuals/compa...

Running the filter search using the idex

In [191]:
search_results = index.search(
    question, 
    boost_dict={"title": 1.0, "text": 2.0},
    filter_dict={"manual": "company-taxation-manual"}, 
    num_results=5
    )

search_results

[{'id': 'ctm00512',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: share capital',
  'text': 'The UK Companies Acts do not define share capital directly but state that references in the Companies Acts to a company having a share capital are to a power under its constitution to issue shares.\xa0 Share capital is the amount appearing in the balance sheet from the issue of shares and if shares are issued at a premium over their nominal value the premium is reflected in a share premium account separate from the nominal share capital, although for both company law purposes (CA06/S610 (4)) and tax law purposes (CTA10/S1025 (2)) the premium is treated as forming part of the share capital for the purposes of its “reduction” under company law and its “repayment” under tax law. This means that share capital reflects the equity (ownership) interests of the company members in their company and, in liquidation, the value of the interests (if any) after creditors have been repaid.\xa0 Historically, share capital reflects shares in the “joint-stock” lying in the hold of a merchant adventurer trading vessel.\xa0 Originally investors owned their own trading stock but as time went on it was held jointly and divided into shares. The important point in modern terms is that share capital, together with share premium, other reserves and undistributed profit, reflects company assets net of liabilities, and thus ownership (not creditor claims). It follows that certificates that simply give rise to an interest in distributions of profit, an income stream, sometimes called “jouissance” shares, are not shares in share capital.\xa0 The French term is used because there is no (common law) English equivalent.\xa0 And the translation of “actions de jouissance” or in German “Genussscheine” is closer to “enjoyment certificates” than to “shares”. A joint-stock company is defined at CA06/S1041 as one that has a permanent paid-up or nominal share capital of fixed amount, divided into shares of fixed amount, or held as transferrable as stock (this means expressed as a monetary sum), or divided partly in one way and partly in another, and is formed on the principle of having for its members the holders of those shares, or that stock, and no other persons if registered with (members’) limited liability is a “company limited by shares”. Members’ liability in the case of a limited company is limited to the nominal amount of the share capital they hold.\xa0 Limited companies are much the most common, for commercial reasons, but companies may be formed without a share capital and members’ liability may be limited by guarantee.\xa0 Companies limited by guarantee are generally formed by non-profit seeking members who nevertheless wish to operate via a corporate entity, and are commonly used for charities.\xa0 Some companies limited by guarantee with a share capital still exist, but since 22 December 1980 (in Great Britain, but 1 July 1983 for Northern Ireland) may no longer be formed. Unlimited companies are fairly rare but continue to be formed due to their limited reporting requirements.\xa0 Their members may choose whether or not to have a share capital. In 1999 the Special Commissioners considered the status of “founders’ deposits” with a company limited by guarantee in the case South Shore Mutual Insurance Co Ltd v Blair 1999 STC (SCD) 296. The Special Commissioners came to the conclusion that the deposits were not issued share capital; the company did not, in fact, have any authorised share capital and, as a consequence, could not have issued share capital. \xa0Companies Act 2006 abolished the requirement for a company to have an authorised share capital with effect from 1 October 2009, but the case contains a useful review of authorities on share capital. See CTM00511 for an introduction to the topic of ordinary share capital.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00512'},
 {'id': 'ctm00511',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: general ',
  'text': "This guidance considers what is meant by “ordinary share capital” and replaces R&C Brief 87/09\xa0published January 2010 also formerly reproduced as CG Manual Appendix 11. That R&C Brief, which succeeded R&C Brief 54/07, was largely focused on whether the balance sheets of foreign entities reflect ordinary share capital or amounts closely analogous to ordinary share capital.\xa0 This is now dealt with at CTM00515 and CTM00516 . \xa0 CTM00512 considers what is meant by “share capital”, CTM00513 what is meant by “shares”, and CTM00514 the meaning of “ordinary shares”. The relevant definitions, for the purposes of the Income Tax Acts at ITA07/S989, and for the purposes of the Corporation Tax Acts at CTA10/S1119, are identical: “Ordinary share capital, in relation to a company, means all the company’s issued share capital (however described), other than capital the holders of which have a right to a dividend at a fixed rate but have no other right to share in the company's profits.” The equivalent definition under company law, found at CA06/S548 is of “equity share capital” and reads “In the Companies Acts “equity share capital”, in relation to a company, means its issued share capital excluding any part of that capital that, neither as respects dividends nor as respects capital, carries any right to participate beyond a specified amount in a distribution.” The tax and company law definitions are quite similar in effect; “distribution” under company law is defined at CA06/S829 in terms that include “every description of distribution of a company’s assets to its members, whether in cash or otherwise” but excludes capital operations such as bonus (capitalisation) issues, capital reductions, redemptions or purchases of shares out of capital and distributions in a winding-up. The Corporation Tax definition of “distribution” at CTA10/PART23 is somewhat broader.\xa0 It reflects anti-avoidance provisions, aimed for example at certain interest payments which have the character of profit distributions, and covers some capital operations.\xa0 But the tax definition above focuses on “dividends”. See CTM00514 regarding certain special definitions of ordinary share capital. Types of share capital The reference in the tax definition to “however described” reflects the fact that commercial practice employs a variety of descriptions of types of share capital which broadly describe their characteristics but are not definitive without reference to the articles or other constitutional documents of the issuing company.\xa0 Examples are deferred ordinary shares; participating preferred ordinary shares; participating preference shares.\xa0 Sometimes shares will be labelled “non-voting”, “redeemable”, “cumulative” or “convertible”.\xa0 These are helpful pointers, but the articles must always be consulted. Member and shareholder Member and shareholder do not always mean the same thing, though usually they do.\xa0 A member is one of the owners of a company (or whatever nature) whose name has been entered on the register of members. Members delegate various powers to the company’s directors to run the company on their behalf. A shareholder is a person who subscribes for or buys and holds shares in a company having a share capital, who becomes a member once their name is entered on the register of members. Companies limited by guarantee do not have a share capital, save for some historical exceptions (see CTM00512 ) and consequently their members are not shareholders but guarantor owners. Whether an overseas-registered entity is treated as being a company in the first instance depends on whether or not it is treated as being “transparent” for tax purposes.\xa0 This aspect is dealt with in the International Manual at INTM180010 onwards.",
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00511'},
 {'id': 'ctm00516',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: share capital: foreign registered companies: particular issues',
  'text': 'Certificates To take an example, a Limited Liability Company (LLC) organised under the law of a US state may issue transferrable interests analogous to shares in share capital but these will not necessarily be evidenced by a certificate of interest (see US Revised Uniform Limited Liability Company Act, Section 502(d)).\xa0 If there are no certificates, this is not necessarily fatal to the conclusion that the members’ interests are analogous to shares in ordinary share capital, provided (as would be expected to be the case) that the interests are clearly defined and recognisable as equity (ownership) interests in the entity. No nominal capital Since the 1960s there has been an international move away from the “capital maintenance” approach still central to UK company law.\xa0 Some US jurisdictions, the California Corporations Code for example, dispense with the concept of nominal capital and others, for example Delaware, allow the issue of shares with nil nominal value.\xa0 A similar approach has been adopted in a number of other jurisdictions.\xa0 Such shares may be referred to as “zero par” shares or simply “zeroes”. An adaptable and pragmatic approach is adopted when dealing with overseas company law which does not straightforwardly align with that of the UK (although UK tax and company law are distinct, aspects of UK Corporation Tax law are unmistakably based on the company law capital maintenance principle, for example the distributions code at CTA10/PART23, see CTM00511 ). Where there is no nominal capital requirement under overseas law, an amount on the facts subscribed as fixed capital analogous to share premium over nil nominal value shares will be treated as share capital by analogy with CTA10/S1025 (2) for the purposes of determining repayment of share capital. Continental (civil law) “partnerships” with share capital Such an institution as a French société en commandite par actions may often be translated as a “limited partnership with a share capital” into English.\xa0 The word “société” is in fact indeterminate and cannot be definitively translated as company or partnership for the purposes of UK tax law, but the share capital aspect reflects its nature as a société de capitaux \xa0 (in civil law generally, Latin intuitu pecuniae – compare the reference to intuitu personae at CTM00515 ).\xa0 This is consistent with the classification of a French SCA as opaque at INTM180030 . See CTM00511 for an introduction to the topic of ordinary share capital.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00516'},
 {'id': 'ctm00515',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: share capital: foreign registered companies',
  'text': 'The UK tax rules are based on UK company law.\xa0 This means that companies formed under foreign law will usually require analysis of at least some of their features by comparison and analogy with the UK Companies Acts. In Ryall v The Du Bois Co Ltd (1933) 18 TC431, Lord Hanworth MR said, “a share in a foreign company may be something different from and, indeed, is almost necessarily different from, a share as we know it in an incorporated company”, and Slesser LJ said, “we have to consider what would be analogous to stocks and shares in Germany in dealing with what is a company, and allowing for differences of law in that country”.\xa0 Approach by analogy is applied generally in addressing foreign registered companies. The key feature of issued share capital is that the issuing body has full legal personality separate and distinct from that of its members, able to carry on business and to own assets in its own right.\xa0 This establishes proprietorial interest through the holding of issued share capital in the body in contrast to partnership interests.\xa0 In UK partnership law partnership property is held and applied by the partners for the purposes of the partnership (PA1890/S20 (1)) and the partnership is the relation between the persons carrying on the business with view to profit (PA1890/S1 (1)). (In Scotland a firm is generally regarded as a "legal person" distinct from its members, PA1890/S4 (2), but S1 (1) and S20 (1) still apply.\xa0 This is because, whether partnership property is held in the name of the firm, or in the name of partner or partners, the persons ultimately beneficially interested in it are the partners according to their partnership rights – per The Scottish Land Court SLC/248/04) following an examination of the authorities.\xa0 Partnerships established under Continental civil law present similar challenges; their “legal personality” may mask what is under civil law known as intuitu personae , or originating in the persons). Capital in this context means a contribution that provides the contributor with an equity interest in (that is, part ownership of) the body, as reflected in the proportion and nature of shares held in the fixed capital.\xa0 CA06/S5 (3), in considering the remaining class of companies limited by guarantee with a share capital (see CTM00512 ), observes that any provision that divides a company’s undertaking into shares or interests is a provision for share capital. This means dividing the company itself, its “corpus”, as referred to in Rae v Lazard Investment Co Ltd (1961-64) 41 TC 1.\xa0 An equity or ownership interest in a body is distinguished from a debt claim against it. The Special Commissioners in the South Shore Mutual Insurance case (see CTM00512 ), identified characteristics of “incidents” of share capital, but these are pointers rather than absolute requirements.\xa0 For instance, shares may be non-voting.\xa0 Important incidents, in relation to members’ interests are: whether they are like shares in share capital (a portion of the capital of the corporate body) or like debt (money owed by the body corporate to the members), what proprietary rights characteristic of shares attach to them, both economic and voting, and what responsibilities, how they are legally evidenced in accordance with local law, whether they are denominated in a stated fixed value, whether the members’ interests compose a fixed and certain amount measuring the company’s capital which creditors may look to as security, and whether the members’ interests are capable of transfer and if so whether such a transfer would amount to transferring of a portion of the capital of the company, with attendant proprietary rights and responsibilities (rather than a claim as creditor). Lord Wrenbury, in Singer v Williams [1920] UKHL 386, drew a distinction between a debt security of and a share in a company, explaining that, in the case of a security, the holder has a resort to some property or fund, there are two owners with different claims; while a shareholder has the right to a proportionate share of the assets of the corporation and there is only one owner in relation to that share.\xa0 See CTM00511 for an introduction to the topic of ordinary share capital.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00515'},
 {'id': 'ctm00513',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: what is meant by “shares”',
  'text': 'An incorporated company is a body corporate, a type of legal entity established under legal or royal authority distinct from its member or members and governed by its articles or other constitutional documents, see CTM00510 for background on bodies corporate and the development of Companies Act companies. As the legal entity is distinct from its member or members, their ownership interests must be reflected in some way. An incorporated company (in most cases, see CTM00511 ) has a share capital and its members hold shares in that share capital; shares and share capital should be understood accordingly. On formation, a company with a share capital is required to submit a Statement of Capital and initial shareholdings to the Registrar of Companies, and a Statement of Capital is needed whenever an annual (company) return is filed and at certain other times, such as on a reduction of capital. The company’s assets are owned by the company itself, not by the shareholders individually, although in turn the shareholders as members together have ownership of the company through their “equity”. The shares express the shareholders’ proprietary interest in the company, which as an entity carries on the activities, not the members or shareholders. In principle, shares are transferable, but in practice there are often restrictions on transfer, set out in the company’s articles or other constitutional documents. The principal rights that usually attach to a share are – the right to dividends (of profits) declared, the right to vote, and the right to share in the company’s assets in a winding-up. The principal liability that attaches to a share is to pay what is due on it. The rights and liabilities are all subject to the company’s articles or other constitutional documents, and there is no debtor/creditor relationship between a company and its members until distribution out of assets takes place. Lord Millett gives a useful summary of the “juridical nature of a share” in IRC v Laird Group plc [2003] UKHL 54 at [37]. Shares are often described as a bundle (or “fasciculus”) of rights and liabilities. See Lord Wright in Lowry v Consolidated African Selection Trust Ltd (1938-41) 23 TC 259 at 298. For the purposes of CTA10/PART23 (definition of distribution in the Corporation Tax Acts) “share” includes stock and any other interest of a member in a company. Issue and allotment of shares Possession of a share certificate is prima facie evidence of ownership of a share, CA06/S127. This does not, of itself, confirm ownership and certificates are not essential to demonstrate that share capital has been issued. However, in order to be a member of a company under the UK Companies Acts, a person must be entered in the company’s register of members, CA06/S112. From 30 June 2016 certain private companies can report changes of membership to Companies House to be reflected in a public register rather than keeping their own. The issue of share capital is only complete when the processes of application, allotment and issue are complete: National Westminster Bank plc v IRC [1994] STC 580. Shares are allotted when a person acquires the unconditional right to be included in the company’s register of members: CA06/S554. TCGA92/S288 (5) provides that, for chargeable gains purposes, shares are treated as issued if they are to be issued under the terms of an unconditional letter of allotment or similar instrument. See CTM00511 for an introduction to the topic of ordinary share capital. CTM00514 considers when shares meet the definition of “ordinary share capital”.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00513'}]

In [192]:
search_results = index.search(
    question, 
    boost_dict={"title": 1.0, "text": 2.0},
    filter_dict={"manual": "vat-registration-manual"}, 
    num_results=5
    )

search_results

[{'id': 'vatreg02650',
  'manual': 'vat-registration-manual',
  'title': 'Basic principles of registration: definition of a capital asset',
  'text': 'The case of Verbond van Nederlandse Ondernemingen v Inspecteur der Invoerrechten en Accijnzen CJEC [1977] 1 CMLR 413, heard by the CJEC gave a broad definition of a capital good: it may be tangible or intangible it must be used for the purpose of some business activity it must be durable it must be of such value that its acquisition costs are not treated as current expenditure but are written off over a number of years. The term ‘capital assets’ therefore covers goods and services which have been used in a business as ‘equipment’. It includes premises, plant, machinery, office machinery, computers, office furniture, used company cars, patent rights which have been exploited and which are sold outright, and goodwill. Legal cases on capital assets The Tribunal in the case of The Trustees of the Mellerstain Trust, EDN/89/41 VTD 4256 decided that the disposal of pictures on display to the public in an historic house was a sale of capital assets. However, in another case, ‘Company X’, solicitors’ advice was that pictures held as an investment were not capital assets. In the Mellerstain Trust case, the paintings were deemed to be a capital asset because they were used to make taxable supplies: they were hung in a house which was open to the paying public. In the case of ‘Company X’, the paintings were not used to make taxable supplies, but were bought as investment assets by an investment company and formed part of the stock of the company. Milk Quotas The giving up of a milk quota is regarded as the surrender of a right to produce a certain quantity of milk and is considered a service. Generally, disposals of milk quotas which have been used for the purpose of some business activity are not considered to be sales of capital assets: so they may render the trader liable to register. If the transfer of a milk quota is linked with a supply of land, it is considered as a single supply for VAT purposes. The liability of the quota follows the liability of the land and the conditions in VATREG02600 will need to be considered. Sale of fishing and similar rights The sale of these rights normally gives purchasers an ‘interest in’ or ‘right over’ land. However, the liability of the supply will depend on whether they are disposed of on their own or sold or leased with land and the conditions in VATREG02600 will need to be considered.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/vat-registration-manual/vatreg02650'},
 {'id': 'vatreg02600',
  'manual': 'vat-registration-manual',
  'title': 'Basic principles of registration: disposals of capital assets',
  'text': 'Paragraph 1(7) of Schedule 1 to the VAT Act 1994 provides that, when determining taxable turnover, the value of supplies of capital assets used in the course of the business (for example, buildings, equipment or vehicles) must be disregarded\xa0(see VATREG02650 ). However, under paragraph 1(8) of Schedule 1, this disregard does not apply to a supply of a capital asset consisting of an interest in, right over, or licence to occupy land where that supply is taxable other than at the zero rate; such supplies must be included in taxable turnover. It should be noted that\xa0a liability to register for VAT may arise under Schedule 3A where a business makes ‘relevant supplies’ of capital assets in the UK. A ‘relevant supply’ is defined in paragraph 9 of Schedule 3A (see\xa0 VATREG39000 )\xa0 Please note that the disposal of stock and capital assets to a person who is acquiring a business as a going concern is, in certain circumstances, not a taxable supply. For further guidance see VTOGC . (External users can access this manual at http://www.hmrc.gov.uk/manuals/vtogcmanual/index.htm ).',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/vat-registration-manual/vatreg02600'},
 {'id': 'vatreg40300',
  'manual': 'vat-registration-manual',
  'title': 'Registration in respect of acquisitions from other Member States: the acquisition threshold',
  'text': 'The acquisition threshold is set at the same level as the normal UK VAT registration threshold. It is the combined total of relevant acquisitions from all EU Member States which counts towards the threshold. The value of the relevant acquisitions is exclusive of any VAT charged in another Member State on the goods being acquired. Unlike the normal VAT registration threshold, the threshold for acquisition tax is based on relevant acquisitions made in a calendar year from 1 January to 31 December.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/vat-registration-manual/vatreg40300'},
 {'id': 'vatreg09100',
  'manual': 'vat-registration-manual',
  'title': 'Entity to be registered: partnerships: registration of trusts as partnerships',
  'text': 'Where more than one person holds title to land or property, section 34 of the Law of Property Act 1925 deems that a statutory trust for sale exists. Where those persons commercially exploit such land or property, a liability to register for VAT may arise (subject to the normal registration rules). As it is only the owners who are able to commercially exploit the land or property (letting, development, and so on), any VAT registration must be effected in joint names. There is no specific provision for the registration of trusts, so any joint registration must either be as a partnership (VAT Act 1994, section 45) or as some form of unincorporated association (VAT Act 1994, section 46). Legal advice suggests that the most appropriate option is to treat co-owners as a partnership for VAT purposes. In accordance with the legal opinion, where co-owners become liable to register for VAT, they should be registered as a partnership for VAT purposes. However, where the co-owners are the same as the partners in a firm, a separate registration will not normally be required. For example, where A, B, C & D are co-owners of land, but are also the partners in a firm of solicitors, they should account for all the activities under one registration. Due to restrictions imposed by the Law of Property Act, title to land and property can only be held in a maximum of four names. This can create a situation where four nominated people hold title to a property on behalf of a larger body, for example, A, B, C & D hold title to a property on behalf of a firm of solicitors A, B, C, D, E & F. Where it is clear that the property is in substance an asset of the larger partnership, we would not require separate registration of the co-owners.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/vat-registration-manual/vatreg09100'},
 {'id': 'vatreg40100',
  'manual': 'vat-registration-manual',
  'title': 'Registration in respect of acquisitions from other Member States: what is an acquisition?',
  'text': 'The VAT Act 1994, Section 11 provides that for a transaction to be an acquisition it must comply with the following conditions: the transaction is a supply of goods (including anything treated for the purposes of the Act as a supply of goods) the transaction involves the removal of the goods from another Member State to the UK.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/vat-registration-manual/vatreg40100'}]

Defining a function to search the index with a question and a course name. The function should return the top 5 results from the index.

In [193]:
def main_search(question, manual="capital-allowances-manual"):
    boost_dict = {"text": 2.0, "title": 1.0}
    filter_dict = {"manual": manual}

    return index.search(
        question,
        boost_dict=boost_dict,
        filter_dict=filter_dict,
        num_results=5
    )
    
    
search_results = main_search(question)
search_results

[{'id': 'ca11530',
  'manual': 'capital-allowances-manual',
  'title': 'General: Definitions: Capital expenditure and capital sums',
  'text': 'CAA01/S4 & CAA01/S572 (3)(b) An amount that the payer can treat as a deduction in computing business profits or which can be allowed as a deduction from the taxable earnings of an employment or office held by the payer is not capital expenditure. An amount that is treated by the recipient as a business receipt or employment income is not a capital sum. Annual payments from which tax should be deducted under ITA/Chapter 6 Part 15 or s906 are not capital expenditure or capital sums. If property is exchanged or if a leasehold interest is surrendered for valuable consideration the transaction is treated as a sale. Where the consideration is not in money, the part of it that would have been a capital sum if it had been paid in money is treated as a capital sum. The purchase price of an asset sometimes includes VAT. If the VAT is allowable as input tax (see BIM31500 onwards) it should be deducted from the capital expenditure. In all other cases, the VAT paid should be included in the capital expenditure. If expenditure on the provision or construction of an asset was revenue expenditure and the asset is later permanently appropriated to fixed assets the expenditure may be pooled for the purpose of claiming WDAs. The expenditure that qualifies for WDAs is the original expenditure incurred and not the market value of the asset at the time of the appropriation. If the original expenditure was incurred in an earlier chargeable period to the period in which the asset is appropriated, the expenditure will not qualify for AIA or FYAs. You should not accept that an asset has been permanently appropriated to fixed assets unless you are satisfied that any profit on sale would be capital rather than revenue.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/capital-allowances-manual/ca11530'},
 {'id': 'ca75100',
  'manual': 'capital-allowances-manual',
  'title': 'Patents: Allowances: Qualifying expenditure',
  'text': 'CAA01/S467 - S469, CAA01/S481 Patent allowances are capital allowances given on capital expenditure incurred on the purchase of patent rights. The current system of patent allowances applies to expenditure incurred on or after 1 April 1986. The system is similar to the system of plant and machinery allowances in that expenditure is normally pooled and allowances are given at an annual rate of 25% on the reducing balance basis. The system for expenditure incurred before 1 April 1986 is described at CA75140 . The expenditure on which patent allowances are given is called qualifying expenditure. Qualifying expenditure is either qualifying trade expenditure or qualifying non-trade expenditure. Qualifying trade expenditure is capital expenditure incurred by a person on the purchase of patent rights for the purposes of a trade within the charge to tax carried on by that person. Pre-trading expenditure on buying patent rights is treated as incurred on the first day of trading provided that the person owns the rights on that date. Qualifying non-trade expenditure is capital expenditure incurred by a person on the purchase of patent rights that is not qualifying trade expenditure provided that income receivable from those rights is liable to tax. Qualifying expenditure is restricted if a person buys patent rights and either: the person buying the rights is connected with the seller, or the sale is a sole or main benefit transaction. A sole or main benefit transaction is one, or one of a series, where the sole or main benefit, which might be expected to accrue to the parties, is the obtaining of a patents allowance. In those cases the buyer’s expenditure qualifying for capital allowances is restricted to: a. the seller’s disposal value if there is one, b. if the seller has no disposal value but receives a capital sum which is chargeable that capital sum, c. if neither (a) nor (b) applies the smallest of: the open market value of the patent rights, where capital expenditure was incurred by the seller, that capital expenditure, where capital expenditure was incurred by anyone connected with the seller his or her capital expenditure.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/capital-allowances-manual/ca75100'},
 {'id': 'ca10040',
  'manual': 'capital-allowances-manual',
  'title': 'History of capital allowances',
  'text': 'The early years The post war system Investment allowances The 1971 system 1984 reforms Developments after 1984 Return of incentive allowances Other new allowances The FA2008 reforms Changes post 2008 Consolidation The early years Until 1878 there were no capital allowances though there were deductions for expenditure incurred in renewing or replacing existing machinery or plant. In 1878 a ‘wear and tear’ deduction was introduced. Wear and tear allowance represented the diminished value of plant and machinery used for trade purposes by reason of wear and tear during the year. The amount allowed was whatever was considered ‘just and reasonable’. A similar deduction based on annual value was available for expenditure on mills and factories. It was called mills and factories allowance. These deductions gave tax relief for an amount broadly equal to the actual economic depreciation suffered. Top of page The post war system The Income Tax Act 1945 put in place a system of capital allowances designed to encourage and assist the reconstruction of British industry after the war. From 1946 the previous system of wear and tear allowances for plant and machinery was replaced by a new system of initial allowances, writing-down allowances, balancing allowances and balancing charges: An initial allowance (i.e. first year allowance) of 20% for plant and machinery for the first year was introduced to encourage investment in new machinery. The annual rate of writing-down allowances for plant and machinery was set at 25%, which was above the rate of depreciation generally considered to be just and reasonable. A balancing adjustment (which could be an allowance or a charge) was made when the asset was sold or ceased to exist to ensure that the overall relief given equalled the actual reduction in value over the period of ownership. The Board of Inland Revenue could fix rates of writing-down allowance for different classes of plant and machinery. The rates were based on the anticipated normal working life of plant and machinery in each class. They were published and could be amended, as required. Industrial buildings allowances replaced the mills and factories allowance. The main features were: An initial allowance of 10% for new buildings for the first year was introduced to encourage investment in new buildings. The annual rate of writing-down allowance was set at 2%. A balancing adjustment (which could be an allowance or a charge) was made when the asset was sold or ceased to exist to ensure that the overall relief given equalled the actual reduction in value over the period of ownership. Industrial buildings and structures that qualified for the new allowances were defined in the legislation. Shops, offices, hotels and dwelling houses were specifically excluded as the purpose of the relief was to ‘help the productive or creative industry that gives industrial employment and is the foundation of national prosperity: from the point of view of national prosperity it is the production of things and the export of things and not the retail distribution at home of things that matters’. Agricultural buildings allowance replaced the special relief given to agricultural landowners under the old Schedule A rules. The rate of allowance was set at 10% (rather than the 2% for industrial buildings) following strong opposition from farmers and landowners to any reduction in the generous relief that they had enjoyed previously. Top of page Investment allowances An ‘investment allowance’ was introduced in 1954 to encourage investment in new plant and machinery, mining works, industrial and agricultural buildings, and buildings and plant used for scientific research. Investment allowances were given in addition to initial and annual allowances. This meant that businesses could receive allowances over the period of ownership of more than the asset had actually cost. The investment allowance was set at a rate of 10% for agricultural and industrial buildings and 20% for other qualifying assets. Investment allowances continued on and off at various rates until 1966. Then they were replaced by direct grants administered by the Board of Trade. The method of making claims for plant and machinery by reference to a wide range of different rates of writing-down allowance set out in published lists continued until 1962. In a move to reduce the burden on business and simplify the process of claiming capital allowances, the number of rates was then reduced to three (15%, 20% and 25%) and taxpayers were allowed to pool expenditure within each category for the purposes of calculating writing-down allowances. This was a considerable simplification, but difficulties still remained where assets were sold or scrapped, as the pool had to be unscrambled to calculate the balancing allowance or charge. Top of page The 1971 system There was a further major simplification in 1971. The number of rates of writing-down allowance for plant and machinery were reduced to just one at 25%. The rules for pooling were extended so as largely to eliminate the need for balancing allowances and charges. This was a considerable simplification and greatly reduced the record- keeping requirements and the number of computations needed for tax purposes. Top of page 1984 reforms In 1984 the then Chancellor of the Exchequer, Nigel Lawson, started a series of reforms to create a more neutral, broader-based tax system. Initial allowances and first year allowances were phased out over three years. The 1984 business tax reforms brought capital allowances closer into line with actual rates of commercial depreciation. Allowances were set at 25% for plant and machinery, 4% for industrial and agricultural buildings. Top of page Developments after 1984 Short-life assets: For assets with lives of less than 4 years, the 25% rate for plant and machinery was recognised as representing less than economic depreciation. To adjust for this, from 1985 taxpayers have been able to elect to keep specific assets out of the general pool. If the asset is then sold or scrapped within 4 years a balancing allowance or charge is made, bringing the allowances given into line with the actual economic depreciation of the asset. Long-life assets: In 1996 the then Government introduced a new 6% rate of allowance for plant and machinery with an expected life of more than 25 years when new. This was a further step towards greater neutrality of the tax system, bringing allowances more closely into line with rates of economic depreciation. The rules only apply to businesses which spend more than £100,000 a year on long-life assets. Top of page Return of incentive allowances First-year allowance for plant and machinery and initial allowances for industrial and agricultural buildings were reintroduced on a temporary basis for expenditure incurred in the year ended 31 October 1993. First-year allowances (FYAs) were introduced again for expenditure incurred by small and medium sized enterprises from 2 July 1998 to April 2008; the rate varied over this period, but was either 40% or 50%. 100% FYAs were introduced for assets purchased by small and medium-sized businesses in the period 12 May 1998 to 11 May 2002 for use primarily in Northern Ireland. Subsequently, other 100% FYAs targeted to encourage particular types of socially desirable investment were introduced for expenditure on: ICT by small businesses, between 1 April 2000 and 31 March 2004; energy-saving plant and machinery, from 1 April 2001 to 1/6 April 2020; cars with low carbon dioxide emissions, from 17 April 2002; plant or machinery for gas refuelling stations, from 17 April 2002; plant or machinery for use wholly in a ring fence trade, from 17 April 2002; environmentally beneficial plant and machinery, from 1 April 2003 to 1/6 April 2020. Top of page Other new allowances Two new codes of allowances (not restricted solely to expenditure on plant or machinery) were introduced in the early years of the 21st century: Flat conversion allowances (FCAs) were introduced by FA2001 (withdrawn in 2013). Business premises renovation allowances (BPRA) were introduced by FA2004, but the scheme did not come into effect until 11 April 2007 (withdrawn in 2017). Top of page The FA2008 reforms The capital allowances changes introduced in FA2008 represented the biggest reform of the capital allowances system since the 1980s. The changes were part of a wider ‘Business Tax Reform’ package, which included a 2% cut in the main rate of corporation tax. The reforms had three main objectives: (1) to promote investment and growth; (2) to reduce distortions and complexity and (3) to maintain fairness and refocus the tax system for smaller businesses. The main capital allowances changes were: The introduction of a new Annual Investment Allowance (AIA), which is effectively a 100% allowance for business expenditure on plant and machinery (apart from cars) up to a maximum threshold per year (£50,000 when the AIA was introduced. The threshold has changed since - see below). The AIA applies to businesses regardless of size, and replaced the previous 40% or 50% FYAS for small and medium-sized businesses only. A new small pools allowance, allowing historic and future pools of plant and machinery expenditure of £1,000 or less to be written-off immediately. New payable tax credits for businesses that make losses attributable to investment in environmentally beneficial plant and machinery. The phased withdrawal of industrial and agricultural buildings allowances by 2011. Changes to the rates of writing down allowances on plant & machinery: from 25% to 20% for the main pool, and from 6% to 10% for long-life assets in the new special rate pool (the WDA rates have changed again since then - see below). The introduction of a new classification of ‘integral features’ of a building or structure to apply to new and replacement expenditure and which will attract allowances in the special rate pool. Top of page Main changes post 2008 The AIA threshold has changed a number of times since the AIA was introduced. For details, see ‘Claim capital allowances - Annual Investment Allowance’, gov.uk . The WDA rates have also changed a number of times. See CA23220 . In 2016 a new first year allowance was introduced for expenditure on the provision of plant and machinery for electric vehicle charge points (see CA23156 ). In 2012/2014 the rules relating to sale of plant and machinery fixtures were changed to ensure that the purchaser cannot usually claim allowances unless the seller has pooled the expenditure and the parties have fixed the disposal value. See CA26470 onwards. In 2018 a structures and buildings allowance was introduced for the cost of constructing and acquiring new non-residential buildings (see CA90000 ). Top of page Consolidation The capital allowance legislation was consolidated in 1990 in CAA90 apart from the legislation on patents and know-how, which stayed in ICTA88. The legislation was rewritten in 2000 and all of the capital allowance legislation is now in CAA2001. You can find CAA2001 and the explanatory notes that go with it on the Intranet or on the Internet at http://www.legislation.gov.uk/ukpga/2001/2/contents .',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/capital-allowances-manual/ca10040'},
 {'id': 'ca93410',
  'manual': 'capital-allowances-manual',
  'title': 'Structures and buildings allowance (SBA): qualifying expenditure: qualifying capital expenditure: qualifying capital expenditure incurred on construction',
  'text': 'CAA01/S270BB Where a person incurs the costs of constructing a building, either directly, or through hiring a building contractor, if they hold the relevant interest when that building is brought into use for the first time, the capital expenditure they incurred on the construction of the building is ‘qualifying capital expenditure’. In other words, the capital expenditure incurred on construction is qualifying capital expenditure if the relevant interest in that building has either: not been sold been sold, but only after the building has been brought into non-residential use. This construction cost will be the amount of qualifying expenditure for each subsequent holder of that relevant interest. See example in CA91400 . Expenditure on renovation or conversion, or on repairs that are incidental to a renovation or conversion, is treated as if it were expenditure on the construction of a building for the first time CA93200 . Fitting out works Capital fitting out costs will qualify for SBA provided all other conditions are met, including that they do not qualify for plant and machinery allowances. If completed at the same time as or as part of the same contract as the construction of the building itself, the costs will be incurred on the same date and the 33 1/3 year claim period will be the same as that of the construction costs for the building. If fitting out works are contracted for and undertaken at a different time to the construction of the building (as will usually be the case for tenanted buildings) the 33 1/3 year claim period for SBA will be different to that of the construction costs for the building itself, and must be claimed separately.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/capital-allowances-manual/ca93410'},
 {'id': 'ca23010',
  'manual': 'capital-allowances-manual',
  'title': 'Plant and Machinery Allowances (PMA): qualifying expenditure: general rule',
  'text': 'CAA01/S11 (4) Expenditure on which PMAs are given is called qualifying expenditure. These are the conditions that must be satisfied for expenditure to be qualifying expenditure for PMAs: The expenditure is capital expenditure on the provision of plant or machinery wholly or partly for the purposes of a qualifying activity that the person incurring the expenditure carries on. The person incurring the expenditure owns the plant or machinery as a result of incurring the expenditure.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/capital-allowances-manual/ca23010'}]

Another use of the search function to search for a question in a different course. The function should return the top 5 results from the index. In this case, using the capital gain manual

In [194]:
def main_search(question, manual="company-taxation-manual"):
    boost_dict = {"text": 2.0, "title": 1.0}
    filter_dict = {"manual": manual}

    return index.search(
        question,
        boost_dict=boost_dict,
        filter_dict=filter_dict,
        num_results=5
    )
    
search_results = main_search(question)
search_results

[{'id': 'ctm00512',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: share capital',
  'text': 'The UK Companies Acts do not define share capital directly but state that references in the Companies Acts to a company having a share capital are to a power under its constitution to issue shares.\xa0 Share capital is the amount appearing in the balance sheet from the issue of shares and if shares are issued at a premium over their nominal value the premium is reflected in a share premium account separate from the nominal share capital, although for both company law purposes (CA06/S610 (4)) and tax law purposes (CTA10/S1025 (2)) the premium is treated as forming part of the share capital for the purposes of its “reduction” under company law and its “repayment” under tax law. This means that share capital reflects the equity (ownership) interests of the company members in their company and, in liquidation, the value of the interests (if any) after creditors have been repaid.\xa0 Historically, share capital reflects shares in the “joint-stock” lying in the hold of a merchant adventurer trading vessel.\xa0 Originally investors owned their own trading stock but as time went on it was held jointly and divided into shares. The important point in modern terms is that share capital, together with share premium, other reserves and undistributed profit, reflects company assets net of liabilities, and thus ownership (not creditor claims). It follows that certificates that simply give rise to an interest in distributions of profit, an income stream, sometimes called “jouissance” shares, are not shares in share capital.\xa0 The French term is used because there is no (common law) English equivalent.\xa0 And the translation of “actions de jouissance” or in German “Genussscheine” is closer to “enjoyment certificates” than to “shares”. A joint-stock company is defined at CA06/S1041 as one that has a permanent paid-up or nominal share capital of fixed amount, divided into shares of fixed amount, or held as transferrable as stock (this means expressed as a monetary sum), or divided partly in one way and partly in another, and is formed on the principle of having for its members the holders of those shares, or that stock, and no other persons if registered with (members’) limited liability is a “company limited by shares”. Members’ liability in the case of a limited company is limited to the nominal amount of the share capital they hold.\xa0 Limited companies are much the most common, for commercial reasons, but companies may be formed without a share capital and members’ liability may be limited by guarantee.\xa0 Companies limited by guarantee are generally formed by non-profit seeking members who nevertheless wish to operate via a corporate entity, and are commonly used for charities.\xa0 Some companies limited by guarantee with a share capital still exist, but since 22 December 1980 (in Great Britain, but 1 July 1983 for Northern Ireland) may no longer be formed. Unlimited companies are fairly rare but continue to be formed due to their limited reporting requirements.\xa0 Their members may choose whether or not to have a share capital. In 1999 the Special Commissioners considered the status of “founders’ deposits” with a company limited by guarantee in the case South Shore Mutual Insurance Co Ltd v Blair 1999 STC (SCD) 296. The Special Commissioners came to the conclusion that the deposits were not issued share capital; the company did not, in fact, have any authorised share capital and, as a consequence, could not have issued share capital. \xa0Companies Act 2006 abolished the requirement for a company to have an authorised share capital with effect from 1 October 2009, but the case contains a useful review of authorities on share capital. See CTM00511 for an introduction to the topic of ordinary share capital.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00512'},
 {'id': 'ctm00511',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: general ',
  'text': "This guidance considers what is meant by “ordinary share capital” and replaces R&C Brief 87/09\xa0published January 2010 also formerly reproduced as CG Manual Appendix 11. That R&C Brief, which succeeded R&C Brief 54/07, was largely focused on whether the balance sheets of foreign entities reflect ordinary share capital or amounts closely analogous to ordinary share capital.\xa0 This is now dealt with at CTM00515 and CTM00516 . \xa0 CTM00512 considers what is meant by “share capital”, CTM00513 what is meant by “shares”, and CTM00514 the meaning of “ordinary shares”. The relevant definitions, for the purposes of the Income Tax Acts at ITA07/S989, and for the purposes of the Corporation Tax Acts at CTA10/S1119, are identical: “Ordinary share capital, in relation to a company, means all the company’s issued share capital (however described), other than capital the holders of which have a right to a dividend at a fixed rate but have no other right to share in the company's profits.” The equivalent definition under company law, found at CA06/S548 is of “equity share capital” and reads “In the Companies Acts “equity share capital”, in relation to a company, means its issued share capital excluding any part of that capital that, neither as respects dividends nor as respects capital, carries any right to participate beyond a specified amount in a distribution.” The tax and company law definitions are quite similar in effect; “distribution” under company law is defined at CA06/S829 in terms that include “every description of distribution of a company’s assets to its members, whether in cash or otherwise” but excludes capital operations such as bonus (capitalisation) issues, capital reductions, redemptions or purchases of shares out of capital and distributions in a winding-up. The Corporation Tax definition of “distribution” at CTA10/PART23 is somewhat broader.\xa0 It reflects anti-avoidance provisions, aimed for example at certain interest payments which have the character of profit distributions, and covers some capital operations.\xa0 But the tax definition above focuses on “dividends”. See CTM00514 regarding certain special definitions of ordinary share capital. Types of share capital The reference in the tax definition to “however described” reflects the fact that commercial practice employs a variety of descriptions of types of share capital which broadly describe their characteristics but are not definitive without reference to the articles or other constitutional documents of the issuing company.\xa0 Examples are deferred ordinary shares; participating preferred ordinary shares; participating preference shares.\xa0 Sometimes shares will be labelled “non-voting”, “redeemable”, “cumulative” or “convertible”.\xa0 These are helpful pointers, but the articles must always be consulted. Member and shareholder Member and shareholder do not always mean the same thing, though usually they do.\xa0 A member is one of the owners of a company (or whatever nature) whose name has been entered on the register of members. Members delegate various powers to the company’s directors to run the company on their behalf. A shareholder is a person who subscribes for or buys and holds shares in a company having a share capital, who becomes a member once their name is entered on the register of members. Companies limited by guarantee do not have a share capital, save for some historical exceptions (see CTM00512 ) and consequently their members are not shareholders but guarantor owners. Whether an overseas-registered entity is treated as being a company in the first instance depends on whether or not it is treated as being “transparent” for tax purposes.\xa0 This aspect is dealt with in the International Manual at INTM180010 onwards.",
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00511'},
 {'id': 'ctm00516',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: share capital: foreign registered companies: particular issues',
  'text': 'Certificates To take an example, a Limited Liability Company (LLC) organised under the law of a US state may issue transferrable interests analogous to shares in share capital but these will not necessarily be evidenced by a certificate of interest (see US Revised Uniform Limited Liability Company Act, Section 502(d)).\xa0 If there are no certificates, this is not necessarily fatal to the conclusion that the members’ interests are analogous to shares in ordinary share capital, provided (as would be expected to be the case) that the interests are clearly defined and recognisable as equity (ownership) interests in the entity. No nominal capital Since the 1960s there has been an international move away from the “capital maintenance” approach still central to UK company law.\xa0 Some US jurisdictions, the California Corporations Code for example, dispense with the concept of nominal capital and others, for example Delaware, allow the issue of shares with nil nominal value.\xa0 A similar approach has been adopted in a number of other jurisdictions.\xa0 Such shares may be referred to as “zero par” shares or simply “zeroes”. An adaptable and pragmatic approach is adopted when dealing with overseas company law which does not straightforwardly align with that of the UK (although UK tax and company law are distinct, aspects of UK Corporation Tax law are unmistakably based on the company law capital maintenance principle, for example the distributions code at CTA10/PART23, see CTM00511 ). Where there is no nominal capital requirement under overseas law, an amount on the facts subscribed as fixed capital analogous to share premium over nil nominal value shares will be treated as share capital by analogy with CTA10/S1025 (2) for the purposes of determining repayment of share capital. Continental (civil law) “partnerships” with share capital Such an institution as a French société en commandite par actions may often be translated as a “limited partnership with a share capital” into English.\xa0 The word “société” is in fact indeterminate and cannot be definitively translated as company or partnership for the purposes of UK tax law, but the share capital aspect reflects its nature as a société de capitaux \xa0 (in civil law generally, Latin intuitu pecuniae – compare the reference to intuitu personae at CTM00515 ).\xa0 This is consistent with the classification of a French SCA as opaque at INTM180030 . See CTM00511 for an introduction to the topic of ordinary share capital.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00516'},
 {'id': 'ctm00515',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: share capital: foreign registered companies',
  'text': 'The UK tax rules are based on UK company law.\xa0 This means that companies formed under foreign law will usually require analysis of at least some of their features by comparison and analogy with the UK Companies Acts. In Ryall v The Du Bois Co Ltd (1933) 18 TC431, Lord Hanworth MR said, “a share in a foreign company may be something different from and, indeed, is almost necessarily different from, a share as we know it in an incorporated company”, and Slesser LJ said, “we have to consider what would be analogous to stocks and shares in Germany in dealing with what is a company, and allowing for differences of law in that country”.\xa0 Approach by analogy is applied generally in addressing foreign registered companies. The key feature of issued share capital is that the issuing body has full legal personality separate and distinct from that of its members, able to carry on business and to own assets in its own right.\xa0 This establishes proprietorial interest through the holding of issued share capital in the body in contrast to partnership interests.\xa0 In UK partnership law partnership property is held and applied by the partners for the purposes of the partnership (PA1890/S20 (1)) and the partnership is the relation between the persons carrying on the business with view to profit (PA1890/S1 (1)). (In Scotland a firm is generally regarded as a "legal person" distinct from its members, PA1890/S4 (2), but S1 (1) and S20 (1) still apply.\xa0 This is because, whether partnership property is held in the name of the firm, or in the name of partner or partners, the persons ultimately beneficially interested in it are the partners according to their partnership rights – per The Scottish Land Court SLC/248/04) following an examination of the authorities.\xa0 Partnerships established under Continental civil law present similar challenges; their “legal personality” may mask what is under civil law known as intuitu personae , or originating in the persons). Capital in this context means a contribution that provides the contributor with an equity interest in (that is, part ownership of) the body, as reflected in the proportion and nature of shares held in the fixed capital.\xa0 CA06/S5 (3), in considering the remaining class of companies limited by guarantee with a share capital (see CTM00512 ), observes that any provision that divides a company’s undertaking into shares or interests is a provision for share capital. This means dividing the company itself, its “corpus”, as referred to in Rae v Lazard Investment Co Ltd (1961-64) 41 TC 1.\xa0 An equity or ownership interest in a body is distinguished from a debt claim against it. The Special Commissioners in the South Shore Mutual Insurance case (see CTM00512 ), identified characteristics of “incidents” of share capital, but these are pointers rather than absolute requirements.\xa0 For instance, shares may be non-voting.\xa0 Important incidents, in relation to members’ interests are: whether they are like shares in share capital (a portion of the capital of the corporate body) or like debt (money owed by the body corporate to the members), what proprietary rights characteristic of shares attach to them, both economic and voting, and what responsibilities, how they are legally evidenced in accordance with local law, whether they are denominated in a stated fixed value, whether the members’ interests compose a fixed and certain amount measuring the company’s capital which creditors may look to as security, and whether the members’ interests are capable of transfer and if so whether such a transfer would amount to transferring of a portion of the capital of the company, with attendant proprietary rights and responsibilities (rather than a claim as creditor). Lord Wrenbury, in Singer v Williams [1920] UKHL 386, drew a distinction between a debt security of and a share in a company, explaining that, in the case of a security, the holder has a resort to some property or fund, there are two owners with different claims; while a shareholder has the right to a proportionate share of the assets of the corporation and there is only one owner in relation to that share.\xa0 See CTM00511 for an introduction to the topic of ordinary share capital.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00515'},
 {'id': 'ctm00513',
  'manual': 'company-taxation-manual',
  'title': 'Introductory: meaning of ordinary share capital: what is meant by “shares”',
  'text': 'An incorporated company is a body corporate, a type of legal entity established under legal or royal authority distinct from its member or members and governed by its articles or other constitutional documents, see CTM00510 for background on bodies corporate and the development of Companies Act companies. As the legal entity is distinct from its member or members, their ownership interests must be reflected in some way. An incorporated company (in most cases, see CTM00511 ) has a share capital and its members hold shares in that share capital; shares and share capital should be understood accordingly. On formation, a company with a share capital is required to submit a Statement of Capital and initial shareholdings to the Registrar of Companies, and a Statement of Capital is needed whenever an annual (company) return is filed and at certain other times, such as on a reduction of capital. The company’s assets are owned by the company itself, not by the shareholders individually, although in turn the shareholders as members together have ownership of the company through their “equity”. The shares express the shareholders’ proprietary interest in the company, which as an entity carries on the activities, not the members or shareholders. In principle, shares are transferable, but in practice there are often restrictions on transfer, set out in the company’s articles or other constitutional documents. The principal rights that usually attach to a share are – the right to dividends (of profits) declared, the right to vote, and the right to share in the company’s assets in a winding-up. The principal liability that attaches to a share is to pay what is due on it. The rights and liabilities are all subject to the company’s articles or other constitutional documents, and there is no debtor/creditor relationship between a company and its members until distribution out of assets takes place. Lord Millett gives a useful summary of the “juridical nature of a share” in IRC v Laird Group plc [2003] UKHL 54 at [37]. Shares are often described as a bundle (or “fasciculus”) of rights and liabilities. See Lord Wright in Lowry v Consolidated African Selection Trust Ltd (1938-41) 23 TC 259 at 298. For the purposes of CTA10/PART23 (definition of distribution in the Corporation Tax Acts) “share” includes stock and any other interest of a member in a company. Issue and allotment of shares Possession of a share certificate is prima facie evidence of ownership of a share, CA06/S127. This does not, of itself, confirm ownership and certificates are not essential to demonstrate that share capital has been issued. However, in order to be a member of a company under the UK Companies Acts, a person must be entered in the company’s register of members, CA06/S112. From 30 June 2016 certain private companies can report changes of membership to Companies House to be reflected in a public register rather than keeping their own. The issue of share capital is only complete when the processes of application, allotment and issue are complete: National Westminster Bank plc v IRC [1994] STC 580. Shares are allotted when a person acquires the unconditional right to be included in the company’s register of members: CA06/S554. TCGA92/S288 (5) provides that, for chargeable gains purposes, shares are treated as issued if they are to be issued under the terms of an unconditional letter of allotment or similar instrument. See CTM00511 for an introduction to the topic of ordinary share capital. CTM00514 considers when shares meet the definition of “ordinary share capital”.',
  'url': 'https://www.gov.uk/hmrc-internal-manuals/company-taxation-manual/ctm00513'}]

----

### Buikding the LLM prompt

In [195]:
INSTRUCTIONS = """
Your task is to answer questions from the manual documents
based on the provided context.

Use the context to find relevant information and provide accurate
answers. If the answer is not found in the context,
respond with \"I don't know.\"
"""

USER_PROMPT_TEMPLATE = """
Question:
{question}

Context:
{context}
"""

In [196]:
def build_context(search_results):
    lines = []

    for doc in search_results:
        lines.append(doc["title"])
        lines.append("guide: " + doc["text"])
        lines.append("")

    return "\n".join(lines).strip()

def build_prompt(question, search_results):
    context = build_context(search_results)
    prompt = USER_PROMPT_TEMPLATE.format(
        question=question,
        context=context
    )
    return prompt.strip()

In [197]:
prompt = build_prompt(question, search_results)
print(prompt)

Question:
What counts as capital expenditure for capital allowances purposes?

Context:
Introductory: meaning of ordinary share capital: share capital
guide: The UK Companies Acts do not define share capital directly but state that references in the Companies Acts to a company having a share capital are to a power under its constitution to issue shares.  Share capital is the amount appearing in the balance sheet from the issue of shares and if shares are issued at a premium over their nominal value the premium is reflected in a share premium account separate from the nominal share capital, although for both company law purposes (CA06/S610 (4)) and tax law purposes (CTA10/S1025 (2)) the premium is treated as forming part of the share capital for the purposes of its “reduction” under company law and its “repayment” under tax law. This means that share capital reflects the equity (ownership) interests of the company members in their company and, in liquidation, the value of the interests (if any) after creditors have been repaid.  Historically, share capital reflects shares in the “joint-stock” lying in the hold of a merchant adventurer trading vessel.  Originally investors owned their own trading stock but as time went on it was held jointly and divided into shares. The important point in modern terms is that share capital, together with share premium, other reserves and undistributed profit, reflects company assets net of liabilities, and thus ownership (not creditor claims). It follows that certificates that simply give rise to an interest in distributions of profit, an income stream, sometimes called “jouissance” shares, are not shares in share capital.  The French term is used because there is no (common law) English equivalent.  And the translation of “actions de jouissance” or in German “Genussscheine” is closer to “enjoyment certificates” than to “shares”. A joint-stock company is defined at CA06/S1041 as one that has a permanent paid-up or nominal share capital of fixed amount, divided into shares of fixed amount, or held as transferrable as stock (this means expressed as a monetary sum), or divided partly in one way and partly in another, and is formed on the principle of having for its members the holders of those shares, or that stock, and no other persons if registered with (members’) limited liability is a “company limited by shares”. Members’ liability in the case of a limited company is limited to the nominal amount of the share capital they hold.  Limited companies are much the most common, for commercial reasons, but companies may be formed without a share capital and members’ liability may be limited by guarantee.  Companies limited by guarantee are generally formed by non-profit seeking members who nevertheless wish to operate via a corporate entity, and are commonly used for charities.  Some companies limited by guarantee with a share capital still exist, but since 22 December 1980 (in Great Britain, but 1 July 1983 for Northern Ireland) may no longer be formed. Unlimited companies are fairly rare but continue to be formed due to their limited reporting requirements.  Their members may choose whether or not to have a share capital. In 1999 the Special Commissioners considered the status of “founders’ deposits” with a company limited by guarantee in the case South Shore Mutual Insurance Co Ltd v Blair 1999 STC (SCD) 296. The Special Commissioners came to the conclusion that the deposits were not issued share capital; the company did not, in fact, have any authorised share capital and, as a consequence, could not have issued share capital.  Companies Act 2006 abolished the requirement for a company to have an authorised share capital with effect from 1 October 2009, but the case contains a useful review of authorities on share capital. See CTM00511 for an introduction to the topic of ordinary share capital.

Introductory: meaning of ordinary share capital: general
guide: This guidance considers what is meant by “ordinary share capital” and replaces R&C Brief 87/09 published January 2010 also formerly reproduced as CG Manual Appendix 11. That R&C Brief, which succeeded R&C Brief 54/07, was largely focused on whether the balance sheets of foreign entities reflect ordinary share capital or amounts closely analogous to ordinary share capital.  This is now dealt with at CTM00515 and CTM00516 .   CTM00512 considers what is meant by “share capital”, CTM00513 what is meant by “shares”, and CTM00514 the meaning of “ordinary shares”. The relevant definitions, for the purposes of the Income Tax Acts at ITA07/S989, and for the purposes of the Corporation Tax Acts at CTA10/S1119, are identical: “Ordinary share capital, in relation to a company, means all the company’s issued share capital (however described), other than capital the holders of which have a right to a dividend at a fixed rate but have no other right to share in the company's profits.” The equivalent definition under company law, found at CA06/S548 is of “equity share capital” and reads “In the Companies Acts “equity share capital”, in relation to a company, means its issued share capital excluding any part of that capital that, neither as respects dividends nor as respects capital, carries any right to participate beyond a specified amount in a distribution.” The tax and company law definitions are quite similar in effect; “distribution” under company law is defined at CA06/S829 in terms that include “every description of distribution of a company’s assets to its members, whether in cash or otherwise” but excludes capital operations such as bonus (capitalisation) issues, capital reductions, redemptions or purchases of shares out of capital and distributions in a winding-up. The Corporation Tax definition of “distribution” at CTA10/PART23 is somewhat broader.  It reflects anti-avoidance provisions, aimed for example at certain interest payments which have the character of profit distributions, and covers some capital operations.  But the tax definition above focuses on “dividends”. See CTM00514 regarding certain special definitions of ordinary share capital. Types of share capital The reference in the tax definition to “however described” reflects the fact that commercial practice employs a variety of descriptions of types of share capital which broadly describe their characteristics but are not definitive without reference to the articles or other constitutional documents of the issuing company.  Examples are deferred ordinary shares; participating preferred ordinary shares; participating preference shares.  Sometimes shares will be labelled “non-voting”, “redeemable”, “cumulative” or “convertible”.  These are helpful pointers, but the articles must always be consulted. Member and shareholder Member and shareholder do not always mean the same thing, though usually they do.  A member is one of the owners of a company (or whatever nature) whose name has been entered on the register of members. Members delegate various powers to the company’s directors to run the company on their behalf. A shareholder is a person who subscribes for or buys and holds shares in a company having a share capital, who becomes a member once their name is entered on the register of members. Companies limited by guarantee do not have a share capital, save for some historical exceptions (see CTM00512 ) and consequently their members are not shareholders but guarantor owners. Whether an overseas-registered entity is treated as being a company in the first instance depends on whether or not it is treated as being “transparent” for tax purposes.  This aspect is dealt with in the International Manual at INTM180010 onwards.

Introductory: meaning of ordinary share capital: share capital: foreign registered companies: particular issues
guide: Certificates To take an example, a Limited Liability Company (LLC) organised under the law of a US state may issue transferrable interests analogous to shares in share capital but these will not necessarily be evidenced by a certificate of interest (see US Revised Uniform Limited Liability Company Act, Section 502(d)).  If there are no certificates, this is not necessarily fatal to the conclusion that the members’ interests are analogous to shares in ordinary share capital, provided (as would be expected to be the case) that the interests are clearly defined and recognisable as equity (ownership) interests in the entity. No nominal capital Since the 1960s there has been an international move away from the “capital maintenance” approach still central to UK company law.  Some US jurisdictions, the California Corporations Code for example, dispense with the concept of nominal capital and others, for example Delaware, allow the issue of shares with nil nominal value.  A similar approach has been adopted in a number of other jurisdictions.  Such shares may be referred to as “zero par” shares or simply “zeroes”. An adaptable and pragmatic approach is adopted when dealing with overseas company law which does not straightforwardly align with that of the UK (although UK tax and company law are distinct, aspects of UK Corporation Tax law are unmistakably based on the company law capital maintenance principle, for example the distributions code at CTA10/PART23, see CTM00511 ). Where there is no nominal capital requirement under overseas law, an amount on the facts subscribed as fixed capital analogous to share premium over nil nominal value shares will be treated as share capital by analogy with CTA10/S1025 (2) for the purposes of determining repayment of share capital. Continental (civil law) “partnerships” with share capital Such an institution as a French société en commandite par actions may often be translated as a “limited partnership with a share capital” into English.  The word “société” is in fact indeterminate and cannot be definitively translated as company or partnership for the purposes of UK tax law, but the share capital aspect reflects its nature as a société de capitaux   (in civil law generally, Latin intuitu pecuniae – compare the reference to intuitu personae at CTM00515 ).  This is consistent with the classification of a French SCA as opaque at INTM180030 . See CTM00511 for an introduction to the topic of ordinary share capital.

Introductory: meaning of ordinary share capital: share capital: foreign registered companies
guide: The UK tax rules are based on UK company law.  This means that companies formed under foreign law will usually require analysis of at least some of their features by comparison and analogy with the UK Companies Acts. In Ryall v The Du Bois Co Ltd (1933) 18 TC431, Lord Hanworth MR said, “a share in a foreign company may be something different from and, indeed, is almost necessarily different from, a share as we know it in an incorporated company”, and Slesser LJ said, “we have to consider what would be analogous to stocks and shares in Germany in dealing with what is a company, and allowing for differences of law in that country”.  Approach by analogy is applied generally in addressing foreign registered companies. The key feature of issued share capital is that the issuing body has full legal personality separate and distinct from that of its members, able to carry on business and to own assets in its own right.  This establishes proprietorial interest through the holding of issued share capital in the body in contrast to partnership interests.  In UK partnership law partnership property is held and applied by the partners for the purposes of the partnership (PA1890/S20 (1)) and the partnership is the relation between the persons carrying on the business with view to profit (PA1890/S1 (1)). (In Scotland a firm is generally regarded as a "legal person" distinct from its members, PA1890/S4 (2), but S1 (1) and S20 (1) still apply.  This is because, whether partnership property is held in the name of the firm, or in the name of partner or partners, the persons ultimately beneficially interested in it are the partners according to their partnership rights – per The Scottish Land Court SLC/248/04) following an examination of the authorities.  Partnerships established under Continental civil law present similar challenges; their “legal personality” may mask what is under civil law known as intuitu personae , or originating in the persons). Capital in this context means a contribution that provides the contributor with an equity interest in (that is, part ownership of) the body, as reflected in the proportion and nature of shares held in the fixed capital.  CA06/S5 (3), in considering the remaining class of companies limited by guarantee with a share capital (see CTM00512 ), observes that any provision that divides a company’s undertaking into shares or interests is a provision for share capital. This means dividing the company itself, its “corpus”, as referred to in Rae v Lazard Investment Co Ltd (1961-64) 41 TC 1.  An equity or ownership interest in a body is distinguished from a debt claim against it. The Special Commissioners in the South Shore Mutual Insurance case (see CTM00512 ), identified characteristics of “incidents” of share capital, but these are pointers rather than absolute requirements.  For instance, shares may be non-voting.  Important incidents, in relation to members’ interests are: whether they are like shares in share capital (a portion of the capital of the corporate body) or like debt (money owed by the body corporate to the members), what proprietary rights characteristic of shares attach to them, both economic and voting, and what responsibilities, how they are legally evidenced in accordance with local law, whether they are denominated in a stated fixed value, whether the members’ interests compose a fixed and certain amount measuring the company’s capital which creditors may look to as security, and whether the members’ interests are capable of transfer and if so whether such a transfer would amount to transferring of a portion of the capital of the company, with attendant proprietary rights and responsibilities (rather than a claim as creditor). Lord Wrenbury, in Singer v Williams [1920] UKHL 386, drew a distinction between a debt security of and a share in a company, explaining that, in the case of a security, the holder has a resort to some property or fund, there are two owners with different claims; while a shareholder has the right to a proportionate share of the assets of the corporation and there is only one owner in relation to that share.  See CTM00511 for an introduction to the topic of ordinary share capital.

Introductory: meaning of ordinary share capital: what is meant by “shares”
guide: An incorporated company is a body corporate, a type of legal entity established under legal or royal authority distinct from its member or members and governed by its articles or other constitutional documents, see CTM00510 for background on bodies corporate and the development of Companies Act companies. As the legal entity is distinct from its member or members, their ownership interests must be reflected in some way. An incorporated company (in most cases, see CTM00511 ) has a share capital and its members hold shares in that share capital; shares and share capital should be understood accordingly. On formation, a company with a share capital is required to submit a Statement of Capital and initial shareholdings to the Registrar of Companies, and a Statement of Capital is needed whenever an annual (company) return is filed and at certain other times, such as on a reduction of capital. The company’s assets are owned by the company itself, not by the shareholders individually, although in turn the shareholders as members together have ownership of the company through their “equity”. The shares express the shareholders’ proprietary interest in the company, which as an entity carries on the activities, not the members or shareholders. In principle, shares are transferable, but in practice there are often restrictions on transfer, set out in the company’s articles or other constitutional documents. The principal rights that usually attach to a share are – the right to dividends (of profits) declared, the right to vote, and the right to share in the company’s assets in a winding-up. The principal liability that attaches to a share is to pay what is due on it. The rights and liabilities are all subject to the company’s articles or other constitutional documents, and there is no debtor/creditor relationship between a company and its members until distribution out of assets takes place. Lord Millett gives a useful summary of the “juridical nature of a share” in IRC v Laird Group plc [2003] UKHL 54 at [37]. Shares are often described as a bundle (or “fasciculus”) of rights and liabilities. See Lord Wright in Lowry v Consolidated African Selection Trust Ltd (1938-41) 23 TC 259 at 298. For the purposes of CTA10/PART23 (definition of distribution in the Corporation Tax Acts) “share” includes stock and any other interest of a member in a company. Issue and allotment of shares Possession of a share certificate is prima facie evidence of ownership of a share, CA06/S127. This does not, of itself, confirm ownership and certificates are not essential to demonstrate that share capital has been issued. However, in order to be a member of a company under the UK Companies Acts, a person must be entered in the company’s register of members, CA06/S112. From 30 June 2016 certain private companies can report changes of membership to Companies House to be reflected in a public register rather than keeping their own. The issue of share capital is only complete when the processes of application, allotment and issue are complete: National Westminster Bank plc v IRC [1994] STC 580. Shares are allotted when a person acquires the unconditional right to be included in the company’s register of members: CA06/S554. TCGA92/S288 (5) provides that, for chargeable gains purposes, shares are treated as issued if they are to be issued under the terms of an unconditional letter of allotment or similar instrument. See CTM00511 for an introduction to the topic of ordinary share capital. CTM00514 considers when shares meet the definition of “ordinary share capital”.

----

In [198]:
# We already built `prompt` in the previous section.
## prompt = build_prompt(question, search_results)

response = openai_client.responses.create(
    model="gpt-5.4-mini",
    input=prompt
)

# The easiest way to read the model answer
print(response.output_text)
print("")

# Optional: inspect token usage
print(response.usage)
print("")

# Example cost estimate for gpt-5.4-mini
input_price = 0.75 / 1_000_000
output_price = 4.50 / 1_000_000

cost = (
    response.usage.input_tokens * input_price +
    response.usage.output_tokens * output_price
)

print(f"Estimated cost: ${cost:.8f}")

For capital allowances purposes, **capital expenditure** is generally expenditure that is **capital in nature rather than revenue in nature**.

In practical terms, it is usually expenditure on:

- **acquiring, constructing or improving** an asset used in the business, such as:
  - plant and machinery
  - buildings or structures that qualify
  - fixtures
  - integral features
  - vehicles and equipment
- **bringing an asset into existence**
- **enhancing or extending** the life, value, or capacity of an existing capital asset

It is **not** usually capital expenditure if it is ordinary day-to-day business spending, such as:

- repairs and maintenance
- staff costs
- rent, rates, and utilities
- routine replacement of consumables
- other revenue expenses

A helpful rule of thumb is:

- **capital expenditure** = spending on a **lasting asset or benefit**
- **revenue expenditure** = spending on the **running of the business**

For capital allowances, the expenditure must usually be incurred **on plant or machinery, or other qualifying assets**, and it must be **capitalised for accounting/tax purposes** rather than deducted immediately as a trading expense.

If you want, I can also give you:
1. the **tax-law test for capital vs revenue**, or
2. examples of what **does and does not qualify** for capital allowances.

ResponseUsage(input_tokens=3711, input_tokens_details=InputTokensDetails(cached_tokens=0, cache_write_tokens=0), output_tokens=286, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=3997)

Estimated cost: $0.00407025

next, let us combined all the code and build a modular function that can be used to search the index and return the top 5 results. The function should take in a question and a course name as parameters. The function should return the top 5 results from the index.

In [210]:
def llm(instructions, user_prompt, model="gpt-5.4-mini"):
    message_history = [
        {"role": "developer", "content": instructions},
        {"role": "user", "content": user_prompt},
    ]

    response = openai_client.responses.create(
        model=model,
        input=message_history,
    )

    return response.output_text


def rag(query, manual='paye-manual', model="gpt-5.4-mini"):
    search_results = main_search(query, manual=manual)
    prompt = build_prompt(query, search_results)
    answer = llm(INSTRUCTIONS, prompt, model=model)
    return answer

In [211]:
answer = rag("How do you gross up a payment for PAYE purposes?")
print(answer)

To gross up a payment for PAYE purposes, calculate the amount needed so the employee ends up with the same net amount after tax and primary Class 1 NICs are deducted.

The method is:

1. Work out the tax and primary Class 1 NICs due on the original amount.
2. Add the employee’s tax rate and primary Class 1 NICs rate together.
3. Subtract that total from 100.
4. Multiply the deductions by 100, then divide by the result from step 3.
5. Add that grossed-up amount to the original expense/benefit.
6. Pay that total through payroll and deduct PAYE and NICs from it.

Example from the guide:
- Original amount: £567
- Tax at 20% = £113.40
- Primary Class 1 NICs at 8% = £45.36
- Total deductions = £158.76

Gross-up calculation:
- £158.76 x 100 = £15,876
- 20 + 8 = 28
- 100 - 28 = 72
- £15,876 / 72 = £220.50

So the grossed-up payment is £220.50, which is added to the original £567, giving £787.50 to be paid through payroll.

In [206]:
df.manual.value_counts().to_dict()

{'paye-manual': 279,
 'vat-registration-manual': 263,
 'company-taxation-manual': 259,
 'capital-gains-manual': 253,
 'capital-allowances-manual': 245}

In [209]:
answer2 = rag( "What are the rules for estimated pay when coding an employee?")
print(answer2)

Estimated pay rules depend on the employment/pension type and whether RTI information is available.

### Main rules
- **Estimated pay is required** for every employment and occupational pension.
- The system usually uses the **latest FPS (RTI)** to calculate it.
- If the latest FPS cannot be used, it will use:
  1. data already held on the system, or
  2. default values.

### If RTI is used, the calculation depends on pay frequency

#### Regular pay
Regular means not marked **Paid Irregularly** or **Paid Annually**.

- **Continuous employment/pension started before CY**
  - Weekly / fortnightly / 4-weekly:
    taxable pay to date ÷ week number × 52
  - Monthly:
    taxable pay to date ÷ month number × 12

- **Mid-year start with a start date**
  - Weekly: pay in period × (52 - week number) + pay in period
  - Fortnightly: pay in period × ((52 - week number) ÷ 2) + pay in period
  - 4-weekly: pay in period × ((52 - week number) ÷ 4) + pay in period
  - If week number is **52 or more**, use **pay in period only**
  - Monthly: pay in period × (12 - month number) + pay in period

- **Mid-year start without a start date**
  - Weekly / fortnightly / 4-weekly:
    pay in period × (52 - week number) + taxable pay to date
  - Monthly:
    pay in period × (12 - month number) + taxable pay to date

#### Paid quarterly
Use the number of days between payment date and 5/4/CY:

- **273 days or more**: taxable pay to date × 4
- **272–182 days**:
  - if taxable pay to date = pay in period: × 3
  - if taxable pay to date > pay in period: ÷ 2 × 4
- **181–91 days**:
  - if taxable pay to date = pay in period: × 2
  - if taxable pay to date > pay in period: taxable pay to date + pay in period
- **90 days or less**: use taxable pay to date

#### Paid biannually
- **182 days or more**: pay in period × 2
- **181 days or less**: use taxable pay to date

#### Annual or one-off payments
- Use the **taxable pay to date** figure on the FPS.

#### Paid irregularly
- If the irregular payment indicator is ticked and the pay frequency is irregular: use **taxable pay to date**
- If the irregular indicator is ticked but frequency is not irregular: use the normal rules for that frequency
- If the indicator is not ticked but pay frequency shows irregular: use **taxable pay to date**

### Ceased employments
- When an employment ceases, CY estimated pay is updated to the **taxable pay to date on the final FPS**
- CY+1 is **not updated**
- In potentially ceased cases without an end date, 5 April is used as the leaving date

### If RTI cannot be used
Use, in order:
1. **IABD estimated pay** for that employment, including £0.00 amounts
2. If none, **default values**:
   - **£15,000** for a primary source
   - **£5,000** for a secondary source

If you want, I can also give the **CY+1 estimated pay rules**.